id: IC3E5554C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T10:34:57+00:00'
last_modified: '2022-06-07T14:11:00.148257+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG04005
  title: བདེ་གཤེགས་བདུན་གྱི་མཆོད་པའི་ཆོག་བསྒྲིགས་ཡིད་བཞིན་དབང་རྒྱལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9461':
      image_group_id: I00KG06678
      title: ''
      total_pages: 208
      order: 1
      base_file: 9461.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
